[package]
edition = "2018"
name = "node"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "1", features = ["serde_json"]}
napi-derive = "1"
rolldown = {path = "../core", version = "0.0.1"}
serde = "1"
serde_derive = "1"
serde_json = "1"

[target.'cfg(all(not(target_arch = "x86_64"), not(target_os = "windows"), not(target_env = "musl")))'.dependencies]
mimalloc-rust = {version = "0.1"}

[target.'cfg(all(target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
snmalloc-rs = {version = "0.2", features = ["16mib", "native-cpu", "usecxx20"]}

[build-dependencies]
napi-build = "1"
