[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "rolldown"
version = "0.0.1"

[[bin]]
bench = false
name = "bundle-lodash-es"
path = "bin/lodash.rs"
test = false

[dependencies.swc_common]
features = ["tty-emitter", "concurrent"]
version = "0.13.1"

[dependencies]
ahash = "0.7"
anyhow = "1"
napi = "1"
napi-derive = "1"
once_cell = "1"
path-absolutize = "3"
rayon = "1"
swc_ecma_ast = "0.54"
swc_ecma_codegen = "0.74"
swc_ecma_parser = "0.73"
swc_ecma_visit = "0.40"
thiserror = "1"
